-- Create the table to store cities in Serbia
CREATE TABLE IF NOT EXISTS cities (
                                      id SERIAL PRIMARY KEY,
                                      city_name VARCHAR(100) NOT NULL
    );

-- Insert all cities in Serbia in alphabetical order
INSERT INTO cities (city_name) VALUES
                                   ('Ada'),
                                   ('Aleksandrovac'),
                                   ('Aleksinac'),
                                   ('Apatin'),
                                   ('Aranđelovac'),
                                   ('Babušnica'),
                                   ('Bač'),
                                   ('Bačka Palanka'),
                                   ('Bačka Topola'),
                                   ('Bački Petrovac'),
                                   ('Bajina Bašta'),
                                   ('Bela Crkva'),
                                   ('Bela Palanka'),
                                   ('Beočin'),
                                   ('Beograd'),
                                   ('Bečej'),
                                   ('Blace'),
                                   ('Bogatić'),
                                   ('Bor'),
                                   ('Bosilegrad'),
                                   ('Brus'),
                                   ('Bujanovac'),
                                   ('Crna Trava'),
                                   ('Ćićevac'),
                                   ('Ćuprija'),
                                   ('Despotovac'),
                                   ('Dimitrovgrad'),
                                   ('Doljevac'),
                                   ('Futog'),
                                   ('Gadžin Han'),
                                   ('Golubac'),
                                   ('Gornji Milanovac'),
                                   ('Inđija'),
                                   ('Irig'),
                                   ('Ivanjica'),
                                   ('Jagodina'),
                                   ('Kanjiža'),
                                   ('Kikinda'),
                                   ('Kladovo'),
                                   ('Knjaževac'),
                                   ('Koceljeva'),
                                   ('Kosjerić'),
                                   ('Kovačica'),
                                   ('Kovin'),
                                   ('Kragujevac'),
                                   ('Kraljevo'),
                                   ('Krupanj'),
                                   ('Kula'),
                                   ('Kuršumlija'),
                                   ('Lajkovac'),
                                   ('Lapovo'),
                                   ('Lazarevac'),
                                   ('Lebane'),
                                   ('Leskovac'),
                                   ('Loznica'),
                                   ('Lučani'),
                                   ('Majdanpek'),
                                   ('Mali Iđoš'),
                                   ('Mali Zvornik'),
                                   ('Medveđa'),
                                   ('Merošina'),
                                   ('Mionica'),
                                   ('Negotin'),
                                   ('Niš'),
                                   ('Nova Crnja'),
                                   ('Nova Pazova'),
                                   ('Nova Varoš'),
                                   ('Novi Bečej'),
                                   ('Novi Kneževac'),
                                   ('Novi Pazar'),
                                   ('Novi Sad'),
                                   ('Obrenovac'),
                                   ('Odžaci'),
                                   ('Opovo'),
                                   ('Osečina'),
                                   ('Palić'),
                                   ('Pančevo'),
                                   ('Paraćin'),
                                   ('Petrovac na Mlavi'),
                                   ('Petrovaradin'),
                                   ('Pirot'),
                                   ('Požarevac'),
                                   ('Požega'),
                                   ('Preševo'),
                                   ('Priboj'),
                                   ('Prijepolje'),
                                   ('Prokuplje'),
                                   ('Rača'),
                                   ('Raška'),
                                   ('Rekovac'),
                                   ('Ruma'),
                                   ('Senta'),
                                   ('Sečanj'),
                                   ('Sjenica'),
                                   ('Smederevo'),
                                   ('Smederevska Palanka'),
                                   ('Sokobanja'),
                                   ('Sombor'),
                                   ('Srbobran'),
                                   ('Sremska Kamenica'),
                                   ('Sremska Mitrovica'),
                                   ('Sremski Karlovci'),
                                   ('Stara Pazova'),
                                   ('Subotica'),
                                   ('Surdulica'),
                                   ('Svilajnac'),
                                   ('Svrljig'),
                                   ('Temerin'),
                                   ('Titel'),
                                   ('Topola'),
                                   ('Trgovište'),
                                   ('Trstenik'),
                                   ('Tutin'),
                                   ('Ub'),
                                   ('Užice'),
                                   ('Valjevo'),
                                   ('Varvarin'),
                                   ('Velika Plana'),
                                   ('Veliko Gradište'),
                                   ('Vladičin Han'),
                                   ('Vladimirci'),
                                   ('Vlasotince'),
                                   ('Vranje'),
                                   ('Vrnjačka Banja'),
                                   ('Vršac'),
                                   ('Žabalj'),
                                   ('Žabari'),
                                   ('Žagubica'),
                                   ('Žitište'),
                                   ('Žitorađa'),
                                   ('Zaječar'),
                                   ('Zlatibor'),
                                   ('Zrenjanin');
