// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"watt-flow/config"
	"watt-flow/db"
	"watt-flow/handler"
	"watt-flow/repository"
	"watt-flow/service"
	"watt-flow/util"
)

// Injectors from wire.go:

func InitDeps(env *config.Environment) *Server {
	logger := util.NewLogger(env)
	database := db.NewDatabase(env, logger)
	userRepository := repository.NewUserRepository(database, logger)
	authService := service.NewAuthService(logger)
	userService := service.NewUserService(userRepository, authService)
	userHandler := handler.NewUserHandler(userService, logger)
	propertyRepository := repository.NewPropertyRepository(database, logger)
	propertyService := service.NewPropertyService(propertyRepository)
	propertyHandler := handler.NewPropertyHandler(propertyService, logger)
	householdRepository := repository.NewHouseholdRepository(database, logger)
	householdService := service.NewHouseholdService(householdRepository)
	householdHandler := handler.NewHouseholdHandler(householdService, logger)
	deviceStatusRepository := repository.NewDeviceStatusRepository(database, logger)
	deviceStatusService := service.NewDeviceStatusService(deviceStatusRepository)
	deviceStatusHandler := handler.NewDeviceStatusHandler(deviceStatusService, logger)
	server := NewServer(logger, userService, authService, userHandler, propertyService, propertyHandler, householdService, householdHandler, deviceStatusService, deviceStatusHandler, database)
	return server
}

// wire.go:

var userServiceSet = wire.NewSet(service.NewUserService, wire.Bind(new(service.IUserService), new(*service.UserService)))

var propertyServiceSet = wire.NewSet(service.NewPropertyService, wire.Bind(new(service.IPropertyService), new(*service.PropertyService)))

var householdServiceSet = wire.NewSet(service.NewHouseholdService, wire.Bind(new(service.IHouseholdService), new(*service.HouseholdService)))

var deviceStatusServiceSet = wire.NewSet(service.NewDeviceStatusService, wire.Bind(new(service.IDeviceStatusService), new(*service.DeviceStatusService)))
