// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"watt-flow/config"
	"watt-flow/db"
	"watt-flow/handler"
	"watt-flow/repository"
	"watt-flow/service"
	"watt-flow/util"
)

// Injectors from wire.go:

func InitDeps(env *config.Environment) *Server {
	logger := util.NewLogger(env)
	database := db.NewDatabase(env, logger)
	userRepository := repository.NewUserRepository(database, logger)
	authService := service.NewAuthService(logger)
	userService := service.NewUserService(userRepository, authService)
	restartService := service.NewRestartService(database, userService)
	userHandler := handler.NewUserHandler(userService, logger)
	propertyRepository := repository.NewPropertyRepository(database, logger)
	householdRepository := repository.NewHouseholdRepository(database, logger)
	ownershipRepository := repository.NewOwnershipRepository(database, logger)
	householdService := service.NewHouseholdService(householdRepository, ownershipRepository)
	propertyService := service.NewPropertyService(propertyRepository, householdService)
	propertyHandler := handler.NewPropertyHandler(propertyService, logger)
	householdHandler := handler.NewHouseholdHandler(householdService, logger)
	ownershipService := service.NewOwnershipService(householdRepository, ownershipRepository)
	ownershipHandler := handler.NewOwnershipHandler(ownershipService, logger)
	deviceStatusRepository := repository.NewDeviceStatusRepository(database, logger)
	influxQueryHelper := util.NewInfluxQueryHelper(env)
	deviceStatusService := service.NewDeviceStatusService(deviceStatusRepository, influxQueryHelper)
	deviceStatusHandler := handler.NewDeviceStatusHandler(deviceStatusService, logger)
	addressRepository := repository.NewAddressRepository(database, logger)
	addressService := service.NewAddressService(addressRepository)
	addressHandler := handler.NewAddressHandler(addressService, logger)
	timeSlotRepository := repository.NewTimeSlotRepository(database, logger)
	meetingRepository := repository.NewMeetingRepository(database, logger)
	meetingService := service.NewMeetingService(timeSlotRepository, meetingRepository)
	meetingHandler := handler.NewMeetingHandler(meetingService, logger)
	pricelistRepository := repository.NewPricelistRepository(database, logger)
	pricelistService := service.NewPricelistService(pricelistRepository)
	pricelistHandler := handler.NewPricelistHandler(pricelistService, logger)
	cityRepository := repository.NewCityRepository(database, logger)
	cityService := service.NewCityService(cityRepository)
	cityHandler := handler.NewCityHandler(cityService, logger)
	server := NewServer(logger, userService, authService, restartService, userHandler, propertyService, propertyHandler, householdService, householdHandler, ownershipService, ownershipHandler, deviceStatusService, deviceStatusHandler, addressService, addressHandler, meetingService, meetingHandler, pricelistService, pricelistHandler, cityService, cityHandler, database)
	return server
}

// wire.go:

var userServiceSet = wire.NewSet(service.NewUserService, wire.Bind(new(service.IUserService), new(*service.UserService)))

var propertyServiceSet = wire.NewSet(service.NewPropertyService, wire.Bind(new(service.IPropertyService), new(*service.PropertyService)))

var householdServiceSet = wire.NewSet(service.NewHouseholdService, wire.Bind(new(service.IHouseholdService), new(*service.HouseholdService)))

var ownershipServiceSet = wire.NewSet(service.NewOwnershipService, wire.Bind(new(service.IOwnershipService), new(*service.OwnershipService)))

var deviceStatusServiceSet = wire.NewSet(service.NewDeviceStatusService, wire.Bind(new(service.IDeviceStatusService), new(*service.DeviceStatusService)))

var addressServiceSet = wire.NewSet(service.NewAddressService, wire.Bind(new(service.IAddressService), new(*service.AddressService)))

var cityServiceSet = wire.NewSet(service.NewCityService, wire.Bind(new(service.ICityService), new(*service.CityService)))

var meetingServiceSet = wire.NewSet(service.NewMeetingService, wire.Bind(new(service.IMeetingService), new(*service.MeetingService)))

var pricelistServiceSet = wire.NewSet(service.NewPricelistService, wire.Bind(new(service.IPricelistService), new(*service.PricelistService)))
