// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"watt-flow/config"
	"watt-flow/controller"
	"watt-flow/db"
	"watt-flow/repository"
	"watt-flow/service"
	"watt-flow/util"
)

// Injectors from wire.go:

func InitDeps(env *config.Environment) *Server {
	logger := util.NewLogger(env)
	database := db.NewDatabase(env, logger)
	userRepository := repository.NewUserRepository(database, logger)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService, logger)
	server := NewServer(logger, userService, userController)
	return server
}

// wire.go:

var userServiceSet = wire.NewSet(service.NewUserService, wire.Bind(new(service.IUserService), new(*service.UserService)))
